export enum AbsenteeismHierarchyTypeEnum {
  HOMOGENEOUS_GROUP = 'HOMOGENEOUS_GROUP',
  WORKSPACE = 'WORKSPACE',
  DIRECTORY = 'DIRECTORY',
  MANAGEMENT = 'MANAGEMENT',
  SECTOR = 'SECTOR',
  SUB_SECTOR = 'SUB_SECTOR',
  OFFICE = 'OFFICE',
  SUB_OFFICE = 'SUB_OFFICE',
}
