-- AlterEnum
ALTER TYPE "RiskSubTypeEnum" ADD VALUE 'AMBIENTAIS';
ALTER TYPE "RiskSubTypeEnum" ADD VALUE 'BIOMECANICOS';
ALTER TYPE "RiskSubTypeEnum" ADD VALUE 'MOBILIARIO_EQUIPAMENTOS';
ALTER TYPE "RiskSubTypeEnum" ADD VALUE 'ORGANIZACIONAIS';

-- AlterEnum
ALTER TYPE "RiskSubTypeEnum" ADD VALUE 'INDICADORES_SAUDE';
ALTER TYPE "RiskSubTypeEnum" ADD VALUE 'INDICADORES_CONTROLES';
