import { IColumnRuleMap } from '../../../types/IFileFactory.types';


export enum CompanyStructRSDataNRHeaderEnum {
  TIPO = 'Tipo ****TIPO',
  UNIDADE = 'Unidade Marítima ****UNIDADE',
  CNPJ = 'CNPJ/CPF/CEI/CAEPF ****CNPJ',
  CODIGO_SETOR = 'Código Setor ****CODIGO_SETOR',
  SETOR = 'Setor ****SETOR',
  CODIGO_SETOR_D = 'Código Setor Desenvolvido ****CODIGO_SETOR_D',
  SETOR_D = 'Setor Desenvolvido ****SETOR_D',
  CODIGO_GHE = 'Código GHE ****CODIGO_GHE',
  GHE = 'GHE ****GHE',
  CODIGO_CARDO = 'Código Cargo ****CODIGO_CARDO',
  CARGO = 'Cargo ****CARGO',
  CODIGO_CARGO_D = 'Código Cargo Desenvolvido ****CODIGO_CARGO_D',
  CARGO_D = 'Cargo Desenvolvido ****CARGO_D',
  CODIGO_PT = 'Código Posição Trabalho ****CODIGO_PT',
  POSICAO = 'Posição Trabalho ****POSICAO',
  INICIO = '*Inicio ****INICIO',
  FIM = 'Fim ****FIM',
  ANEXO = '*Anexo ****ANEXO',
  TECNICA = '*Técnica  ****TECNICA',
  EXPOSICAO = '*Exposição ****EXPOSICAO',
  MEDIÇAO_PORTARIA = 'Medição (critério Portaria MTE 3214/78) ****MEDIÇAO_PORTARIA',
  MEDIÇAO_INSS = 'Medição (conf. critério INSS) ****MEDIÇAO_INSS',
  INTENSIDADE_RUIDO = 'Intensidade ****INTENSIDADE_RUIDO',
  TIPO_LEITURA = 'Tipo de leitura ****TIPO_LEITURA',
  RESULTADO = 'Resultado IBUTG ****RESULTADO',
  TIPO_ATIVIDADE = 'Tipo Atividade ****TIPO_ATIVIDADE',
  KCAL = 'Kcal/h Atividade ****KCAL',
  REGIME = 'Regime de Trabalho (por hora) ****REGIME',
  LOCAL = 'Local de Descanso no ambiente de Trabalho ****LOCAL',
  LIMITE_IBUTG = 'Limite IBUTG ****LIMITE_IBUTG',
  INTENSIDADE_RAD = 'Intensidade ****INTENSIDADE_RAD',
  TIPO_VIBRACAO = 'Tipo Vibracao ****TIPO_VIBRACAO',
  CORPO = 'Corpo Inteiro Posição ****CORPO',
  INTENSIDADE_AREN = 'Intensidade (aren) ****INTENSIDADE_AREN',
  INTENSIDADE_VDVR = 'Intensidade (VDVR) ****INTENSIDADE_VDVR',
  LIMITE_FRIO = 'Limite de Tolerância ****LIMITE_FRIO',
  INTENSIDADE_FRIO = 'Intensidade ****INTENSIDADE_FRIO',
  AGENTE_QUI = 'Agente ****AGENTE_QUI',
  INTENSIDADE_QUI = 'Intensidade ****INTENSIDADE_QUI',
  UNIDADE_MEDIDA = 'Unidade ****UNIDADE_MEDIDA',
  AGENTE_POEIRA = 'Agente ****AGENTE_POEIRA',
  INTENSIDADE_POEIRA = 'Intensidade ****INTENSIDADE_POEIRA',
  UNIDADE_POEIRA = 'Unidade ****UNIDADE_POEIRA',
  AGENTE_QUI_ANEXO_13 = 'Agente ****AGENTE_QUI_ANEXO_13',
  MANIPULAÇAO_ANEXO_13 = 'Manipulação ****MANIPULAÇAO_ANEXO_13',
  AGENTE_RESTO = 'Agente ****AGENTE_RESTO',
  FATOR_ELET_RAD = 'Fator de Risco ****FATOR_ELET_RAD',
  TAREFA_ELET_RAD = 'Tarefa ****TAREFA_ELET_RAD',
  CONSTAR_EM = '*Constar em ****CONSTAR_EM',
  CONSIDERAR_PCMSO = '*Considerar acima do nível de ação para PCMSO ****CONSIDERAR_PCMSO',
  NAO_CONSIDERAR_COMPLEMENTARES = '*Não considerar Exames Complementares ****NAO_CONSIDERAR_COMPLEMENTARES',
  EPI = 'EPI eficaz ****EPI',
  CA = 'Cas ****CA',
  EPI_EFICAZ = 'Uso Efetivo ****EPI_EFICAZ',
  EPI_TREINAMENTO = 'Treinamento ****EPI_TREINAMENTO',
  EPI_REGISTRO = 'Registro em Ficha ****EPI_REGISTRO',
  EPI_1 = 'Optou-se pela utilização do EPI após a tentativa de implementação de EPCs ****EPI_1',
  EPI_2 = 'Foram observadas as condições de funcionamento do EPI ao longo do tempo? ****EPI_2',
  EPI_3 = 'Foi observado o uso ininterrupto do EPI ao longo do tempo? ****EPI_3',
  EPI_4 = 'Foi observado o prazo de validade do Certificado de Aprovação - CA do MTb no momento da compra do EPI? ****EPI_4',
  EPI_5 = 'Foi observada a periodicidade de troca definida pelo fabricante? ****EPI_5',
  EPI_6 = 'Foi observada a higienização conforme orientação do fabricante? ****EPI_6',
  EPI_7 = 'Foi observado o prazo de validade do produto? Segue instruções de uso, manuseio e armazenamento? (NT 110:2016 e NT 146:2015) ****EPI_7',
  AGENTE_EQUIVALENTE = 'Agente Equivalente ****AGENTE_EQUIVALENTE',
  FONTE_GERADORA = 'Fonte Geradora ****FONTE_GERADORA',
  MEIO_PROP = 'Meio de Propagação ****MEIO_PROP',
  COMPROMETIMENTO = 'Comprometimento à Saúde ****COMPROMETIMENTO',
  POSSIVEIS_DANOS = 'Possíveis Danos à Saúde ****POSSIVEIS_DANOS',
  MEDIDAS_CONTROLE = 'Medidas de Controle ****MEDIDAS_CONTROLE',
  VIAS_ABS = 'Vias de Absorção ****VIAS_ABS',
  RECOMENDACOES = 'Recomendações ****RECOMENDACOES',
  OBSERVACOES = 'Observações ****OBSERVACOES',
  ETAPA = 'Etapa ****ETAPA',
  CODIGO = 'Código Integração Empresa ****CODIGO',
}

export const CompanyStructRSDataNRColumnMap: IColumnRuleMap<any> = {
  ...Object.values(CompanyStructRSDataNRHeaderEnum).reduce((acc, key) => ({
    ...acc,
    [key]: {
      field: key,
      database: key,
    },
  }), {}),
};
