import { IColumnRuleMap } from '../../../types/IFileFactory.types';


export enum CompanyStructRSDataNRHeaderEnum {
  TIPO = 'Tipo',
  UNIDADE = 'Unidade Marítima',
  CNPJ = 'CNPJ/CPF/CEI/CAEPF',
  CODIGO_SETOR = 'Código Setor',
  SETOR = 'Setor',
  CODIGO_SETOR_D = 'Código Setor Desenvolvido',
  SETOR_D = 'Setor Desenvolvido',
  CODIGO_GHE = 'Código GHE',
  GHE = 'GHE',
  CODIGO_CARDO = 'Código Cargo',
  CARGO = 'Cargo',
  CODIGO_CARGO_D = 'Código Cargo Desenvolvido',
  CARGO_D = 'Cargo Desenvolvido',
  CODIGO_PT = 'Código Posição Trabalho',
  POSICAO = 'Posição Trabalho',
  INICIO = '*Inicio',
  FIM = 'Fim',
  ANEXO = '*Anexo',
  TECNICA = '*Técnica ',
  EXPOSICAO = '*Exposição',
  MEDIÇAO_PORTARIA = 'Medição (critério Portaria MTE 3214/78)',
  MEDIÇAO_INSS = 'Medição (conf. critério INSS)',
  INTENSIDADE_RUIDO = 'Intensidade',
  TIPO_LEITURA = 'Tipo de leitura',
  RESULTADO = 'Resultado IBUTG',
  TIPO_ATIVIDADE = 'Tipo Atividade',
  KCAL = 'Kcal/h Atividade',
  REGIME = 'Regime de Trabalho (por hora)',
  LOCAL = 'Local de Descanso no ambiente de Trabalho',
  LIMITE_IBUTG = 'Limite IBUTG',
  INTENSIDADE_RAD = 'Intensidade',
  TIPO_VIBRACAO = 'Tipo Vibracao',
  CORPO = 'Corpo Inteiro Posição',
  INTENSIDADE_AREN = 'Intensidade (aren)',
  INTENSIDADE_VDVR = 'Intensidade (VDVR)',
  LIMITE_FRIO = 'Limite de Tolerância',
  INTENSIDADE_FRIO = 'Intensidade',
  AGENTE_QUI = 'Agente',
  INTENSIDADE_QUI = 'Intensidade',
  UNIDADE_MEDIDA = 'Unidade',
  AGENTE_POEIRA = 'Agente',
  INTENSIDADE_POEIRA = 'Intensidade',
  UNIDADE_POEIRA = 'Unidade',
  AGENTE_QUI_ANEXO_13 = 'Agente',
  MANIPULAÇAO_ANEXO_13 = 'Manipulação',
  AGENTE_RESTO = 'Agente',
  FATOR_ELET_RAD = 'Fator de Risco',
  TAREFA_ELET_RAD = 'Tarefa',
  CONSTAR_EM = '*Constar em',
  CONSIDERAR_PCMSO = '*Considerar acima do nível de ação para PCMSO',
  NAO_CONSIDERAR_COMPLEMENTARES = '*Não considerar Exames Complementares',
  EPI = 'EPI eficaz',
  CA = 'Cas',
  EPI_EFICAZ = 'Uso Efetivo',
  EPI_TREINAMENTO = 'Treinamento',
  EPI_REGISTRO = 'Registro em Ficha',
  EPI_1 = 'Optou-se pela utilização do EPI após a tentativa de implementação de EPCs',
  EPI_2 = 'Foram observadas as condições de funcionamento do EPI ao longo do tempo?',
  EPI_3 = 'Foi observado o uso ininterrupto do EPI ao longo do tempo?',
  EPI_4 = 'Foi observado o prazo de validade do Certificado de Aprovação - CA do MTb no momento da compra do EPI?',
  EPI_5 = 'Foi observada a periodicidade de troca definida pelo fabricante?',
  EPI_6 = 'Foi observada a higienização conforme orientação do fabricante?',
  EPI_7 = 'Foi observado o prazo de validade do produto? Segue instruções de uso, manuseio e armazenamento? (NT 110:2016 e NT 146:2015)',
  AGENTE_EQUIVALENTE = 'Agente Equivalente',
  FONTE_GERADORA = 'Fonte Geradora',
  MEIO_PROP = 'Meio de Propagação',
  COMPROMETIMENTO = 'Comprometimento à Saúde',
  POSSIVEIS_DANOS = 'Possíveis Danos à Saúde',
  MEDIDAS_CONTROLE = 'Medidas de Controle',
  VIAS_ABS = 'Vias de Absorção',
  RECOMENDACOES = 'Recomendações',
  OBSERVACOES = 'Observações',
  ETAPA = 'Etapa',
  CODIGO = 'Código Integração Empresa',
}

export const CompanyStructRSDataNRColumnMap: IColumnRuleMap<any> = {
  ...Object.values(CompanyStructRSDataNRHeaderEnum).reduce((acc, key) => ({
    ...acc,
    [key]: {
      field: key,
      database: key,
    },
  }), {}),
};
