-- AlterEnum
ALTER TYPE "SystemAiPromptKeyEnum" ADD VALUE IF NOT EXISTS 'RISK_FACTOR_PHYSICAL_AI_SUGGESTIONS';
ALTER TYPE "SystemAiPromptKeyEnum" ADD VALUE IF NOT EXISTS 'RISK_FACTOR_BIOLOGICAL_AI_SUGGESTIONS';
ALTER TYPE "SystemAiPromptKeyEnum" ADD VALUE IF NOT EXISTS 'RISK_FACTOR_ERGONOMIC_AI_SUGGESTIONS';
ALTER TYPE "SystemAiPromptKeyEnum" ADD VALUE IF NOT EXISTS 'RISK_FACTOR_ACCIDENT_AI_SUGGESTIONS';
ALTER TYPE "SystemAiPromptKeyEnum" ADD VALUE IF NOT EXISTS 'RISK_FACTOR_OTHER_AI_SUGGESTIONS';
