export enum CacheEnum {
  ESOCIAL_FETCH_EVENT = 'ESOCIAL_FETCH_EVENT',
  REC_MED_REPRESENT_ALL = 'REC_MED_REPRESENT_ALL',
  GS_REPRESENT_ALL = 'GS_REPRESENT_ALL',
  ALERT_NOTIFICATION = 'ALERT_NOTIFICATION_:type_:companyId',
  ALERT_CRON = 'ALERT_CRON',
  PUBLIC_FORM_APPLICATION = 'PUBLIC_FORM_APPLICATION',
  AI_RISKS_KNOWLEDGE_BASE = 'AI_RISKS_KNOWLEDGE_BASE',
}
