export enum SoapClientEnum {
  PRODUCTION = 'PRODUCTION',
  PRODUCTION_RESTRICT = 'PRODUCTION_RESTRICT',
  CONSULT_PRODUCTION = 'CONSULT_PRODUCTION',
  CONSULT_PRODUCTION_RESTRICT = 'CONSULT_PRODUCTION_RESTRICT',
}
