export enum DocumentSectionTypeEnum {
  CHAPTER = 'CHAPTER',
  TOC = 'TOC',
  COVER = 'COVER',
  SECTION = 'SECTION',
  APR = 'APR',
  APR_GROUP = 'APR_GROUP',
  ACTION_PLAN = 'ACTION_PLAN',
  ITERABLE_ENVIRONMENTS = 'ITERABLE_ENVIRONMENTS',
  ITERABLE_CHARACTERIZATION = 'ITERABLE_CHARACTERIZATION',
  PERICULOSIDADE_ACTIVITIES = 'PERICULOSIDADE_ACTIVITIES',
}
